stages:
  - test
  - build
  - deploy
  - dast

variables:
  DOCKER_IMAGE_TAG: alanhohn/todo
  DBUSER: todo
  DBPASS: todo

test:
  stage: test
  image: node:10
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - package-lock.json
      - npm-audit.json
  services:
    - name: postgres:12
      alias: db
  variables:
    POSTGRES_DB: todo
    POSTGRES_USER: "${DBUSER}"
    POSTGRES_PASS: "${DBPASS}"
    DATABASE_URL: "postgres://${DBUSER}:${DBPASS}@db/todo"
  script:
    - ./ci-test.sh

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $REGISTRY_USER -p REGISTRY_TOKEN 
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
